apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-gke
  template:
    metadata:
      labels:
        app: sample-gke
    spec:
      containers:
        - name: sample-gke
          image: gcr.io/burner-tanazad1/sample-gke:latest  # Use the correct image tag
          ports:
            - containerPort: 8080
          env:
            - name: REDISHOST
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: host
            - name: REDISPORT
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: port